// generated by pack_sprites.py — do not edit
#pragma once
#include <cstdint>

#define SPR_W 64
#define SPR_H 72
#define SPR_TRANSPARENT 0xF81F

struct ActionMeta { const char* name; uint8_t frames; uint8_t fps; bool loop; };
static const int ACTION_COUNT = 34;
static const ActionMeta ACTIONS[] = {
  { "idle", 6, 6, true },
  { "walking", 6, 10, true },
  { "running", 6, 14, true },
  { "jumping", 6, 9, false },
  { "flying", 6, 10, true },
  { "landing", 6, 9, false },
  { "blast", 6, 10, false },
  { "chest_blast", 8, 9, false },
  { "missile_launch", 6, 10, false },
  { "laser_attack", 6, 10, false },
  { "charging", 8, 10, true },
  { "victory", 6, 8, false },
  { "low_battery", 6, 4, true },
  { "damaged", 6, 12, true },
  { "repairing", 6, 8, false },
  { "upgrading", 8, 10, false },
  { "dancing", 8, 10, true },
  { "eating", 6, 7, false },
  { "drinking", 6, 7, false },
  { "sleeping", 6, 4, true },
  { "exercising", 6, 8, true },
  { "reading", 6, 4, true },
  { "playing", 6, 9, true },
  { "waving", 6, 10, false },
  { "hugging", 6, 7, true },
  { "giving_heart", 6, 7, false },
  { "romantic", 6, 6, true },
  { "happy", 6, 9, true },
  { "sad", 6, 5, true },
  { "angry", 6, 14, true },
  { "surprised", 6, 9, false },
  { "thinking", 6, 5, true },
  { "sleepy", 6, 5, true },
  { "in_love", 6, 7, true },
};
