#!/usr/bin/env python3
"""Pack the sprite frames in sprites_src/ into the device format:
- one .bin per action (goes into firmware/data/sprites/ -> LittleFS, also copied to SD):
    [uint16 frame_count][per frame: 64*72 uint16 RGB565 ...]
  transparent pixels (alpha=0) -> colour key 0xF81F; semi-transparent -> composited on black.
- generates firmware/src/sprites_meta.h: frame W/H + per-action frames/fps/loop table.

Bring your own character: replace sprites_src/ with your own frames in the same layout
(sprites_src/metadata.json + sprites_src/frames/<action>/<action>_<i>.png, RGBA 64x72),
or run `python tools/gen_sprites.py` first to (re)generate the bundled generic mascot.

Usage (from repo root):  python tools/pack_sprites.py
"""
import json, os, struct
from PIL import Image

SRC = "sprites_src"
OUT_BIN = "firmware/data/sprites"
OUT_HDR = "firmware/src/sprites_meta.h"
KEY = 0xF81F  # 透明色键(品红,素材里不会出现)

def to565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

meta = json.load(open(SRC + "/metadata.json"))
FW, FH = meta["frame_w"], meta["frame_h"]
os.makedirs(OUT_BIN, exist_ok=True)

order = []
for batch in meta["batches"].values():
    order += batch

total = 0
for act in order:
    n = meta["actions"][act]["frames"]
    words = [n]  # 头:帧数
    for i in range(n):
        im = Image.open(f"{SRC}/frames/{act}/{act}_{i}.png").convert("RGBA")
        assert im.size == (FW, FH), (act, im.size)
        px = im.load()
        for y in range(FH):
            for x in range(FW):
                r, g, b, a = px[x, y]
                if a == 0:
                    words.append(KEY)
                else:  # 合成到黑底,保留发光质感
                    words.append(to565(r * a // 255, g * a // 255, b * a // 255))
    data = struct.pack(f"<{len(words)}H", *words)
    open(f"{OUT_BIN}/{act}.bin", "wb").write(data)
    total += len(data)

with open(OUT_HDR, "w") as f:
    f.write("// generated by pack_sprites.py — do not edit\n#pragma once\n#include <cstdint>\n\n")
    f.write(f"#define SPR_W {FW}\n#define SPR_H {FH}\n#define SPR_TRANSPARENT 0x{KEY:04X}\n\n")
    f.write("struct ActionMeta { const char* name; uint8_t frames; uint8_t fps; bool loop; };\n")
    f.write(f"static const int ACTION_COUNT = {len(order)};\n")
    f.write("static const ActionMeta ACTIONS[] = {\n")
    for act in order:
        a = meta["actions"][act]
        f.write(f'  {{ "{act}", {a["frames"]}, {a["fps"]}, {str(a["loop"]).lower()} }},\n')
    f.write("};\n")

print(f"packed {len(order)} actions, {total} bytes ({total/1024/1024:.2f} MB)")
print(f"  bins -> {OUT_BIN}/")
print(f"  header -> {OUT_HDR}")
